# Generated by Django 3.0.8 on 2020-07-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("author", models.CharField(blank=True, max_length=128, null=True)),
                ("author_email", models.EmailField(max_length=254)),
                (
                    "bugtrack_url",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "classifiers",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "description_content_type",
                    models.CharField(blank=True, max_length=128),
                ),
                ("docs_url", models.CharField(blank=True, max_length=512, null=True)),
                ("download_url", models.CharField(blank=True, max_length=512)),
                ("downloads", models.CharField(max_length=512)),
                ("home_page", models.CharField(blank=True, max_length=512, null=True)),
                ("keywords", models.CharField(blank=True, max_length=1024)),
                ("license", models.CharField(blank=True, max_length=256)),
                ("maintainer", models.CharField(blank=True, max_length=256)),
                ("maintainer_email", models.EmailField(blank=True, max_length=254)),
                ("name", models.CharField(blank=True, max_length=256)),
                ("package_url", models.CharField(blank=True, max_length=256)),
                ("platform", models.CharField(blank=True, max_length=128)),
                ("project_url", models.CharField(blank=True, max_length=256)),
                ("project_urls", models.CharField(blank=True, max_length=1024)),
                ("release_url", models.CharField(blank=True, max_length=256)),
                (
                    "requires_dist",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("requires_python", models.CharField(blank=True, max_length=64)),
                ("summary", models.CharField(blank=True, max_length=256)),
                ("version", models.CharField(max_length=32)),
                ("yanked", models.BooleanField()),
                (
                    "yanked_reason",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("releases", models.CharField(max_length=2048)),
            ],
        ),
    ]
